services:
  sensor_viz:
    user: "${UID:-1000}:${GID:-1000}"
    build:
      context: ..
      dockerfile: .docker/Dockerfile
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ${XAUTHORITY:-~/.Xauthority}:/root/.Xauthority
      - ..:/app
    environment:
      - DISPLAY=${DISPLAY}
      - XAUTHORITY=/root/.Xauthority
      - QT_X11_NO_MITSHM=1
    network_mode: "host"
    privileged: true
    ipc: host  # Add this for X11 shared memory
    stdin_open: true  # Enable stdin
    tty: true        # Enable terminal
    command: bash -c "python3 /app/scripts/viz.py"

  tof_error_metrics:
    user: "${UID:-1000}:${GID:-1000}"
    extends: sensor_viz
    depends_on:
      - sensor_viz
    command: bash -c "python3 /app/scripts/tof_error_analysis.py"

  calibration:
    user: "${UID:-1000}:${GID:-1000}"
    extends: sensor_viz
    depends_on:
      - sensor_viz
    command: bash -c "python3 /app/scripts/calibration.py"